services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  waitlist:
    build: ./waitlist
    ports:
      - "5003:5003"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - RABBITMQ_HOST=rabbitmq
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
  registration:
    build: ./registration
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  event:
    build: ./event
    ports:
      - "5001:5001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  volunteer:
    build: ./volunteer
    ports:
      - "5002:5002"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  organiser:
    build: ./organiser
    ports:
      - "5004:5004"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  register_for_event:
    build: ./register_for_event
    ports:
      - "5010:5010"
    environment:
      - REGISTRATION_URL=http://registration:5000
      - EVENT_URL=http://event:5001
      - VOLUNTEER_URL=http://volunteer:5002
      - WAITLIST_URL=http://waitlist:5003
      - RABBITMQ_HOST=active-white-bear-01.rmq6.cloudamqp.com
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=ntxsydfp
      - RABBITMQ_USER=ntxsydfp
      - RABBITMQ_PASS=VRMsjW_248ItCPA3gSjNFl51HfiO1Dt9
    depends_on:
      - event
      - volunteer
      - registration
      - waitlist
      - rabbitmq
    restart: always

  delete_registration:
    build: ./delete_registration
    ports:
      - "5011:5011"
    environment:
      - REGISTRATION_URL=http://registration:5000
      - EVENT_URL=http://event:5001
      - VOLUNTEER_URL=http://volunteer:5002
      - WAITLIST_URL=http://waitlist:5003
      - RABBITMQ_HOST=active-white-bear-01.rmq6.cloudamqp.com
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=ntxsydfp
      - RABBITMQ_USER=ntxsydfp
      - RABBITMQ_PASS=VRMsjW_248ItCPA3gSjNFl51HfiO1Dt9
    depends_on:
      - event
      - volunteer
      - registration
      - waitlist
      - rabbitmq
    restart: always

  get_event_by_volunteer:
    build: ./get_event_by_volunteer
    ports:
      - "5012:5012"
    environment:
      - REGISTRATION_URL=http://registration:5000
      - EVENT_URL=http://event:5001
      - VOLUNTEER_URL=http://volunteer:5002
      - WAITLIST_URL=http://waitlist:5003
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - event
      - volunteer
      - registration
      - waitlist
      - rabbitmq
    restart: always
    

